# you need to add GH_TOKEN added in Travis https://docs.travis-ci.com/user/deployment/pages/
sudo: false
dist: trusty
language: rust
cache: cargo
rust:
- stable
branches:
  only:
  - master
before_script:
- "(test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)"
- (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
- cargo install-update -a
script:
- mdbook test
- mdbook build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: book
  keep_history: false
  on:
    branch: master
